// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: webinfo.proto

package webinfo_service_v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//信息列表
type InfoReq struct {
	PageNum              int64    `protobuf:"varint,1,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Filter               string   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Order                string   `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	Unscoped             bool     `protobuf:"varint,5,opt,name=unscoped,proto3" json:"unscoped,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoReq) Reset()         { *m = InfoReq{} }
func (m *InfoReq) String() string { return proto.CompactTextString(m) }
func (*InfoReq) ProtoMessage()    {}
func (*InfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfb2e4482474456, []int{0}
}
func (m *InfoReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InfoReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoReq.Merge(m, src)
}
func (m *InfoReq) XXX_Size() int {
	return m.Size()
}
func (m *InfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoReq proto.InternalMessageInfo

func (m *InfoReq) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *InfoReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *InfoReq) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *InfoReq) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *InfoReq) GetUnscoped() bool {
	if m != nil {
		return m.Unscoped
	}
	return false
}

type InfoResp struct {
	Total                int64         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Lists                []*InfoDetail `protobuf:"bytes,2,rep,name=lists,proto3" json:"lists,omitempty"`
	Page                 int64         `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size_                int32         `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InfoResp) Reset()         { *m = InfoResp{} }
func (m *InfoResp) String() string { return proto.CompactTextString(m) }
func (*InfoResp) ProtoMessage()    {}
func (*InfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfb2e4482474456, []int{1}
}
func (m *InfoResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InfoResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResp.Merge(m, src)
}
func (m *InfoResp) XXX_Size() int {
	return m.Size()
}
func (m *InfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResp proto.InternalMessageInfo

func (m *InfoResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *InfoResp) GetLists() []*InfoDetail {
	if m != nil {
		return m.Lists
	}
	return nil
}

func (m *InfoResp) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *InfoResp) GetSize_() int32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

//信息详情
type InfoDetail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sn                   string   `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	WebKey               string   `protobuf:"bytes,3,opt,name=web_key,json=webKey,proto3" json:"web_key,omitempty"`
	UniqueVal            string   `protobuf:"bytes,4,opt,name=unique_val,json=uniqueVal,proto3" json:"unique_val,omitempty"`
	WebVal               string   `protobuf:"bytes,5,opt,name=web_val,json=webVal,proto3" json:"web_val,omitempty"`
	Status               int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Ord                  string   `protobuf:"bytes,11,opt,name=ord,proto3" json:"ord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoDetail) Reset()         { *m = InfoDetail{} }
func (m *InfoDetail) String() string { return proto.CompactTextString(m) }
func (*InfoDetail) ProtoMessage()    {}
func (*InfoDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfb2e4482474456, []int{2}
}
func (m *InfoDetail) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InfoDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InfoDetail.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InfoDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoDetail.Merge(m, src)
}
func (m *InfoDetail) XXX_Size() int {
	return m.Size()
}
func (m *InfoDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoDetail.DiscardUnknown(m)
}

var xxx_messageInfo_InfoDetail proto.InternalMessageInfo

func (m *InfoDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InfoDetail) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *InfoDetail) GetWebKey() string {
	if m != nil {
		return m.WebKey
	}
	return ""
}

func (m *InfoDetail) GetUniqueVal() string {
	if m != nil {
		return m.UniqueVal
	}
	return ""
}

func (m *InfoDetail) GetWebVal() string {
	if m != nil {
		return m.WebVal
	}
	return ""
}

func (m *InfoDetail) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *InfoDetail) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *InfoDetail) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *InfoDetail) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *InfoDetail) GetOrd() string {
	if m != nil {
		return m.Ord
	}
	return ""
}

//添加/修改信息
type SaveInfoReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sn                   string   `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	WebKey               string   `protobuf:"bytes,3,opt,name=web_key,json=webKey,proto3" json:"web_key,omitempty" validate:"required"`
	UniqueVal            string   `protobuf:"bytes,4,opt,name=unique_val,json=uniqueVal,proto3" json:"unique_val,omitempty" validate:"required"`
	WebVal               string   `protobuf:"bytes,5,opt,name=web_val,json=webVal,proto3" json:"web_val,omitempty" validate:"required"`
	Status               int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" validate:"min=0"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" validate:"min=0"`
	DeletedAt            int64    `protobuf:"varint,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Ord                  string   `protobuf:"bytes,11,opt,name=ord,proto3" json:"ord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveInfoReq) Reset()         { *m = SaveInfoReq{} }
func (m *SaveInfoReq) String() string { return proto.CompactTextString(m) }
func (*SaveInfoReq) ProtoMessage()    {}
func (*SaveInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfb2e4482474456, []int{3}
}
func (m *SaveInfoReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SaveInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SaveInfoReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SaveInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveInfoReq.Merge(m, src)
}
func (m *SaveInfoReq) XXX_Size() int {
	return m.Size()
}
func (m *SaveInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_SaveInfoReq proto.InternalMessageInfo

func (m *SaveInfoReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SaveInfoReq) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *SaveInfoReq) GetWebKey() string {
	if m != nil {
		return m.WebKey
	}
	return ""
}

func (m *SaveInfoReq) GetUniqueVal() string {
	if m != nil {
		return m.UniqueVal
	}
	return ""
}

func (m *SaveInfoReq) GetWebVal() string {
	if m != nil {
		return m.WebVal
	}
	return ""
}

func (m *SaveInfoReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SaveInfoReq) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *SaveInfoReq) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *SaveInfoReq) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *SaveInfoReq) GetOrd() string {
	if m != nil {
		return m.Ord
	}
	return ""
}

//公共save/delete 响应
type SaveResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResp) Reset()         { *m = SaveResp{} }
func (m *SaveResp) String() string { return proto.CompactTextString(m) }
func (*SaveResp) ProtoMessage()    {}
func (*SaveResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfb2e4482474456, []int{4}
}
func (m *SaveResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SaveResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SaveResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SaveResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResp.Merge(m, src)
}
func (m *SaveResp) XXX_Size() int {
	return m.Size()
}
func (m *SaveResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResp.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResp proto.InternalMessageInfo

func (m *SaveResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SaveResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *SaveResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//删除记录
type DelInfoReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" validate:"required"`
	Physical             bool     `protobuf:"varint,2,opt,name=physical,proto3" json:"physical,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelInfoReq) Reset()         { *m = DelInfoReq{} }
func (m *DelInfoReq) String() string { return proto.CompactTextString(m) }
func (*DelInfoReq) ProtoMessage()    {}
func (*DelInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbfb2e4482474456, []int{5}
}
func (m *DelInfoReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelInfoReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelInfoReq.Merge(m, src)
}
func (m *DelInfoReq) XXX_Size() int {
	return m.Size()
}
func (m *DelInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelInfoReq proto.InternalMessageInfo

func (m *DelInfoReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DelInfoReq) GetPhysical() bool {
	if m != nil {
		return m.Physical
	}
	return false
}

func init() {
	proto.RegisterType((*InfoReq)(nil), "webinfo.service.v1.InfoReq")
	proto.RegisterType((*InfoResp)(nil), "webinfo.service.v1.InfoResp")
	proto.RegisterType((*InfoDetail)(nil), "webinfo.service.v1.InfoDetail")
	proto.RegisterType((*SaveInfoReq)(nil), "webinfo.service.v1.SaveInfoReq")
	proto.RegisterType((*SaveResp)(nil), "webinfo.service.v1.SaveResp")
	proto.RegisterType((*DelInfoReq)(nil), "webinfo.service.v1.DelInfoReq")
}

func init() { proto.RegisterFile("webinfo.proto", fileDescriptor_dbfb2e4482474456) }

var fileDescriptor_dbfb2e4482474456 = []byte{
	// 785 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4f, 0x6f, 0xd3, 0x48,
	0x14, 0x5f, 0x3b, 0xff, 0xa7, 0xda, 0xdd, 0x6a, 0xb6, 0x6a, 0xad, 0xb4, 0x9b, 0x46, 0xbe, 0x6c,
	0xb4, 0xab, 0x7a, 0xba, 0xcd, 0xaa, 0x87, 0x4a, 0x7b, 0x68, 0xb7, 0x2b, 0x81, 0x40, 0x08, 0x5c,
	0x01, 0xc7, 0x32, 0x8e, 0x27, 0xee, 0x08, 0xc7, 0x76, 0x3c, 0xe3, 0x54, 0x21, 0x0a, 0x48, 0x88,
	0x0b, 0x67, 0x2e, 0x7c, 0x0b, 0xbe, 0x05, 0xe2, 0x88, 0xc4, 0xbd, 0x42, 0x85, 0x4f, 0xd0, 0x33,
	0x07, 0x34, 0x7f, 0x9c, 0x94, 0xa6, 0x69, 0x0f, 0x88, 0x93, 0xdf, 0xef, 0x3d, 0xcf, 0x7b, 0xbf,
	0xf9, 0xcd, 0x7b, 0x0f, 0xfc, 0x7c, 0x4c, 0x3c, 0x1a, 0x75, 0x63, 0x27, 0x49, 0x63, 0x1e, 0x43,
	0x98, 0x43, 0x46, 0xd2, 0x01, 0xed, 0x10, 0x67, 0xf0, 0x77, 0x7d, 0x23, 0xa0, 0xfc, 0x28, 0xf3,
	0x9c, 0x4e, 0xdc, 0x43, 0x41, 0x1c, 0xc4, 0x48, 0xfe, 0xea, 0x65, 0x5d, 0x89, 0x24, 0x90, 0x96,
	0x4a, 0x51, 0x5f, 0x0d, 0xe2, 0x38, 0x08, 0xc9, 0xf4, 0x2f, 0xd2, 0x4b, 0xf8, 0x50, 0x07, 0xd7,
	0x74, 0x10, 0x27, 0x14, 0xe1, 0x28, 0x8a, 0x39, 0xe6, 0x34, 0x8e, 0x98, 0x8a, 0xda, 0x2f, 0x0d,
	0x50, 0xb9, 0x19, 0x75, 0x63, 0x97, 0xf4, 0xa1, 0x05, 0x2a, 0x09, 0x0e, 0xc8, 0x9d, 0xac, 0x67,
	0x19, 0x4d, 0xa3, 0x55, 0x70, 0x73, 0x08, 0xeb, 0xa0, 0x2a, 0xcc, 0x03, 0xfa, 0x84, 0x58, 0x66,
	0xd3, 0x68, 0x95, 0xdc, 0x09, 0x86, 0xcb, 0xa0, 0xdc, 0xa5, 0x21, 0x27, 0xa9, 0x55, 0x68, 0x1a,
	0xad, 0x9a, 0xab, 0x11, 0x5c, 0x02, 0xa5, 0x38, 0xf5, 0x49, 0x6a, 0x15, 0xa5, 0x5b, 0x01, 0x91,
	0x29, 0x8b, 0x58, 0x27, 0x4e, 0x88, 0x6f, 0x95, 0x9a, 0x46, 0xab, 0xea, 0x4e, 0xb0, 0xfd, 0x14,
	0x54, 0x15, 0x15, 0x96, 0x88, 0xd3, 0x3c, 0xe6, 0x38, 0xd4, 0x4c, 0x14, 0x80, 0xff, 0x80, 0x52,
	0x48, 0x19, 0x67, 0x96, 0xd9, 0x2c, 0xb4, 0x16, 0xb6, 0x1a, 0xce, 0xac, 0x76, 0x8e, 0x48, 0xb1,
	0x4f, 0x38, 0xa6, 0xa1, 0xab, 0x7e, 0x86, 0x10, 0x14, 0x05, 0x5b, 0xc9, 0xaf, 0xe0, 0x4a, 0x5b,
	0xf8, 0x98, 0xb8, 0x4d, 0x51, 0xde, 0x46, 0xda, 0xf6, 0x0b, 0x13, 0x80, 0xe9, 0x69, 0xf8, 0x0b,
	0x30, 0xa9, 0xaf, 0xeb, 0x9b, 0xd4, 0x17, 0x98, 0x45, 0xf2, 0xfa, 0x35, 0xd7, 0x64, 0x11, 0x5c,
	0x01, 0x95, 0x63, 0xe2, 0x1d, 0x3e, 0x26, 0xc3, 0xfc, 0xe6, 0xc7, 0xc4, 0xbb, 0x45, 0x86, 0xf0,
	0x77, 0x00, 0xb2, 0x88, 0xf6, 0x33, 0x72, 0x38, 0xc0, 0xa1, 0xbe, 0x7e, 0x4d, 0x79, 0x1e, 0xe0,
	0x30, 0x3f, 0x27, 0x62, 0xa5, 0xc9, 0x39, 0x11, 0x58, 0x06, 0x65, 0xc6, 0x31, 0xcf, 0x98, 0x55,
	0x96, 0xac, 0x34, 0x12, 0xf9, 0x3a, 0x29, 0xc1, 0x9c, 0xf8, 0x87, 0x98, 0x5b, 0x15, 0x49, 0xa8,
	0xa6, 0x3d, 0xbb, 0x5c, 0x96, 0x4b, 0xfc, 0x3c, 0x5c, 0x55, 0x61, 0xed, 0x51, 0x61, 0x9f, 0x84,
	0x44, 0x87, 0x6b, 0x2a, 0xac, 0x3d, 0xbb, 0x1c, 0x2e, 0x82, 0x42, 0x9c, 0xfa, 0xd6, 0x82, 0x64,
	0x22, 0x4c, 0xfb, 0x8b, 0x09, 0x16, 0x0e, 0xf0, 0x80, 0xe4, 0x6d, 0x71, 0x9d, 0x0e, 0x9b, 0x17,
	0x74, 0xd8, 0x5b, 0x39, 0x3b, 0x59, 0xff, 0x6d, 0x80, 0x43, 0x2a, 0x28, 0xec, 0xd8, 0x29, 0xe9,
	0x67, 0x34, 0x25, 0xbe, 0x3d, 0x11, 0x68, 0x7b, 0x56, 0xa0, 0xf9, 0x87, 0xce, 0x29, 0xb7, 0x79,
	0x41, 0xb9, 0xab, 0x2b, 0x5d, 0x25, 0x69, 0x7b, 0x56, 0xd2, 0xbd, 0xa5, 0xb3, 0x93, 0xf5, 0xc5,
	0x69, 0xb2, 0x1e, 0x8d, 0xfe, 0xdd, 0xb4, 0xcf, 0x0b, 0xdd, 0x9e, 0x15, 0x7a, 0xde, 0xa1, 0xef,
	0x90, 0xff, 0x06, 0xa8, 0x0a, 0xf5, 0xe5, 0x14, 0x4c, 0xe9, 0x1b, 0xdf, 0xd0, 0x87, 0xa0, 0xe8,
	0x63, 0x8e, 0xf5, 0x23, 0x48, 0x5b, 0x64, 0xea, 0xb1, 0x40, 0xb7, 0xa2, 0x30, 0xed, 0x7b, 0x00,
	0xec, 0x93, 0x30, 0x7f, 0xc6, 0x3f, 0xa6, 0xcf, 0x38, 0x5f, 0x37, 0xf1, 0xbe, 0x62, 0xd8, 0x8f,
	0x86, 0x8c, 0x76, 0x70, 0x28, 0x0b, 0x54, 0xdd, 0x09, 0xde, 0x7a, 0x5b, 0x04, 0x95, 0x87, 0xc4,
	0x13, 0x39, 0xe1, 0x36, 0x28, 0xde, 0xa5, 0x51, 0x00, 0x97, 0x1d, 0xb5, 0x61, 0x9c, 0x7c, 0xfd,
	0x38, 0xff, 0x8b, 0xf5, 0x53, 0x9f, 0xe3, 0x87, 0x6f, 0x0c, 0x35, 0xe7, 0xb7, 0x29, 0xe3, 0x70,
	0x75, 0xde, 0x08, 0xbb, 0xa4, 0x5f, 0x5f, 0x9b, 0x1f, 0x64, 0x89, 0x7d, 0xf4, 0xfc, 0xc3, 0xe7,
	0x57, 0xa6, 0x07, 0x1f, 0x21, 0xfd, 0x17, 0x12, 0x93, 0x1d, 0x65, 0x3d, 0x34, 0xd2, 0x7b, 0x6b,
	0x2c, 0x3d, 0x62, 0xb6, 0x95, 0x4b, 0xec, 0xab, 0x31, 0x52, 0xfb, 0x09, 0x8d, 0xd4, 0x77, 0x8c,
	0xe4, 0x62, 0x42, 0x23, 0xf9, 0x19, 0xa3, 0x7c, 0x1b, 0xa1, 0x51, 0x6e, 0x8d, 0x61, 0x00, 0xc0,
	0x7f, 0xb2, 0x0b, 0xe4, 0xbd, 0xd7, 0x2f, 0x63, 0x75, 0x6e, 0x60, 0x2e, 0xa7, 0x9d, 0xbf, 0xa9,
	0x5d, 0x97, 0xb4, 0x97, 0xec, 0x5f, 0x27, 0xb4, 0x55, 0x87, 0xed, 0x18, 0x7f, 0x8a, 0x42, 0xf7,
	0x65, 0xe7, 0xfc, 0x98, 0x42, 0xaa, 0x2b, 0x45, 0xa1, 0x67, 0xb2, 0x35, 0x88, 0x2e, 0x74, 0xe9,
	0x1e, 0x9d, 0xb6, 0xce, 0x35, 0x75, 0xda, 0xb2, 0xce, 0x86, 0xfd, 0xd7, 0xa4, 0x8e, 0x6a, 0x6f,
	0x44, 0x7d, 0x34, 0xa2, 0xfe, 0x18, 0xe5, 0xdd, 0x83, 0x46, 0xb9, 0x35, 0xde, 0x5b, 0x7c, 0x77,
	0xda, 0x30, 0xde, 0x9f, 0x36, 0x8c, 0x8f, 0xa7, 0x0d, 0xe3, 0xf5, 0xa7, 0xc6, 0x4f, 0x5e, 0x59,
	0xb6, 0x49, 0xfb, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xf7, 0x49, 0x29, 0x1f, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebInfoClient is the client API for WebInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebInfoClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	InfoList(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error)
	CreateInfo(ctx context.Context, in *SaveInfoReq, opts ...grpc.CallOption) (*SaveResp, error)
	UpdateInfo(ctx context.Context, in *SaveInfoReq, opts ...grpc.CallOption) (*SaveResp, error)
	DeleteInfo(ctx context.Context, in *DelInfoReq, opts ...grpc.CallOption) (*SaveResp, error)
}

type webInfoClient struct {
	cc *grpc.ClientConn
}

func NewWebInfoClient(cc *grpc.ClientConn) WebInfoClient {
	return &webInfoClient{cc}
}

func (c *webInfoClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/webinfo.service.v1.WebInfo/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webInfoClient) InfoList(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error) {
	out := new(InfoResp)
	err := c.cc.Invoke(ctx, "/webinfo.service.v1.WebInfo/InfoList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webInfoClient) CreateInfo(ctx context.Context, in *SaveInfoReq, opts ...grpc.CallOption) (*SaveResp, error) {
	out := new(SaveResp)
	err := c.cc.Invoke(ctx, "/webinfo.service.v1.WebInfo/CreateInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webInfoClient) UpdateInfo(ctx context.Context, in *SaveInfoReq, opts ...grpc.CallOption) (*SaveResp, error) {
	out := new(SaveResp)
	err := c.cc.Invoke(ctx, "/webinfo.service.v1.WebInfo/UpdateInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webInfoClient) DeleteInfo(ctx context.Context, in *DelInfoReq, opts ...grpc.CallOption) (*SaveResp, error) {
	out := new(SaveResp)
	err := c.cc.Invoke(ctx, "/webinfo.service.v1.WebInfo/DeleteInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebInfoServer is the server API for WebInfo service.
type WebInfoServer interface {
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
	InfoList(context.Context, *InfoReq) (*InfoResp, error)
	CreateInfo(context.Context, *SaveInfoReq) (*SaveResp, error)
	UpdateInfo(context.Context, *SaveInfoReq) (*SaveResp, error)
	DeleteInfo(context.Context, *DelInfoReq) (*SaveResp, error)
}

// UnimplementedWebInfoServer can be embedded to have forward compatible implementations.
type UnimplementedWebInfoServer struct {
}

func (*UnimplementedWebInfoServer) Ping(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedWebInfoServer) InfoList(ctx context.Context, req *InfoReq) (*InfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InfoList not implemented")
}
func (*UnimplementedWebInfoServer) CreateInfo(ctx context.Context, req *SaveInfoReq) (*SaveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInfo not implemented")
}
func (*UnimplementedWebInfoServer) UpdateInfo(ctx context.Context, req *SaveInfoReq) (*SaveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInfo not implemented")
}
func (*UnimplementedWebInfoServer) DeleteInfo(ctx context.Context, req *DelInfoReq) (*SaveResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInfo not implemented")
}

func RegisterWebInfoServer(s *grpc.Server, srv WebInfoServer) {
	s.RegisterService(&_WebInfo_serviceDesc, srv)
}

func _WebInfo_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebInfoServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webinfo.service.v1.WebInfo/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebInfoServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebInfo_InfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebInfoServer).InfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webinfo.service.v1.WebInfo/InfoList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebInfoServer).InfoList(ctx, req.(*InfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebInfo_CreateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebInfoServer).CreateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webinfo.service.v1.WebInfo/CreateInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebInfoServer).CreateInfo(ctx, req.(*SaveInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebInfo_UpdateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebInfoServer).UpdateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webinfo.service.v1.WebInfo/UpdateInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebInfoServer).UpdateInfo(ctx, req.(*SaveInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebInfo_DeleteInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebInfoServer).DeleteInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webinfo.service.v1.WebInfo/DeleteInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebInfoServer).DeleteInfo(ctx, req.(*DelInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webinfo.service.v1.WebInfo",
	HandlerType: (*WebInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _WebInfo_Ping_Handler,
		},
		{
			MethodName: "InfoList",
			Handler:    _WebInfo_InfoList_Handler,
		},
		{
			MethodName: "CreateInfo",
			Handler:    _WebInfo_CreateInfo_Handler,
		},
		{
			MethodName: "UpdateInfo",
			Handler:    _WebInfo_UpdateInfo_Handler,
		},
		{
			MethodName: "DeleteInfo",
			Handler:    _WebInfo_DeleteInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webinfo.proto",
}

func (m *InfoReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InfoReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Unscoped {
		i--
		if m.Unscoped {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.Order) > 0 {
		i -= len(m.Order)
		copy(dAtA[i:], m.Order)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.Order)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Filter) > 0 {
		i -= len(m.Filter)
		copy(dAtA[i:], m.Filter)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.Filter)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PageSize != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.PageSize))
		i--
		dAtA[i] = 0x10
	}
	if m.PageNum != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.PageNum))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *InfoResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InfoResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Size_ != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.Size_))
		i--
		dAtA[i] = 0x20
	}
	if m.Page != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Lists) > 0 {
		for iNdEx := len(m.Lists) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Lists[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWebinfo(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Total != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *InfoDetail) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoDetail) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InfoDetail) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Ord) > 0 {
		i -= len(m.Ord)
		copy(dAtA[i:], m.Ord)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.Ord)))
		i--
		dAtA[i] = 0x5a
	}
	if m.DeletedAt != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.DeletedAt))
		i--
		dAtA[i] = 0x48
	}
	if m.UpdatedAt != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x40
	}
	if m.CreatedAt != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x38
	}
	if m.Status != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if len(m.WebVal) > 0 {
		i -= len(m.WebVal)
		copy(dAtA[i:], m.WebVal)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.WebVal)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.UniqueVal) > 0 {
		i -= len(m.UniqueVal)
		copy(dAtA[i:], m.UniqueVal)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.UniqueVal)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.WebKey) > 0 {
		i -= len(m.WebKey)
		copy(dAtA[i:], m.WebKey)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.WebKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sn) > 0 {
		i -= len(m.Sn)
		copy(dAtA[i:], m.Sn)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.Sn)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SaveInfoReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SaveInfoReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SaveInfoReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Ord) > 0 {
		i -= len(m.Ord)
		copy(dAtA[i:], m.Ord)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.Ord)))
		i--
		dAtA[i] = 0x5a
	}
	if m.DeletedAt != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.DeletedAt))
		i--
		dAtA[i] = 0x48
	}
	if m.UpdatedAt != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x40
	}
	if m.CreatedAt != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x38
	}
	if m.Status != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if len(m.WebVal) > 0 {
		i -= len(m.WebVal)
		copy(dAtA[i:], m.WebVal)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.WebVal)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.UniqueVal) > 0 {
		i -= len(m.UniqueVal)
		copy(dAtA[i:], m.UniqueVal)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.UniqueVal)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.WebKey) > 0 {
		i -= len(m.WebKey)
		copy(dAtA[i:], m.WebKey)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.WebKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sn) > 0 {
		i -= len(m.Sn)
		copy(dAtA[i:], m.Sn)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.Sn)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SaveResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SaveResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SaveResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintWebinfo(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if m.Status != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DelInfoReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelInfoReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelInfoReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Physical {
		i--
		if m.Physical {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintWebinfo(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintWebinfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovWebinfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *InfoReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PageNum != 0 {
		n += 1 + sovWebinfo(uint64(m.PageNum))
	}
	if m.PageSize != 0 {
		n += 1 + sovWebinfo(uint64(m.PageSize))
	}
	l = len(m.Filter)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	l = len(m.Order)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	if m.Unscoped {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *InfoResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Total != 0 {
		n += 1 + sovWebinfo(uint64(m.Total))
	}
	if len(m.Lists) > 0 {
		for _, e := range m.Lists {
			l = e.Size()
			n += 1 + l + sovWebinfo(uint64(l))
		}
	}
	if m.Page != 0 {
		n += 1 + sovWebinfo(uint64(m.Page))
	}
	if m.Size_ != 0 {
		n += 1 + sovWebinfo(uint64(m.Size_))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *InfoDetail) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovWebinfo(uint64(m.Id))
	}
	l = len(m.Sn)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	l = len(m.WebKey)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	l = len(m.UniqueVal)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	l = len(m.WebVal)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovWebinfo(uint64(m.Status))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovWebinfo(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovWebinfo(uint64(m.UpdatedAt))
	}
	if m.DeletedAt != 0 {
		n += 1 + sovWebinfo(uint64(m.DeletedAt))
	}
	l = len(m.Ord)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SaveInfoReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovWebinfo(uint64(m.Id))
	}
	l = len(m.Sn)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	l = len(m.WebKey)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	l = len(m.UniqueVal)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	l = len(m.WebVal)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovWebinfo(uint64(m.Status))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovWebinfo(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovWebinfo(uint64(m.UpdatedAt))
	}
	if m.DeletedAt != 0 {
		n += 1 + sovWebinfo(uint64(m.DeletedAt))
	}
	l = len(m.Ord)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SaveResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovWebinfo(uint64(m.Status))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovWebinfo(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DelInfoReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovWebinfo(uint64(m.Id))
	}
	if m.Physical {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovWebinfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWebinfo(x uint64) (n int) {
	return sovWebinfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *InfoReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageNum", wireType)
			}
			m.PageNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PageNum |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageSize", wireType)
			}
			m.PageSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PageSize |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Order = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unscoped", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Unscoped = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipWebinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InfoResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lists", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lists = append(m.Lists, &InfoDetail{})
			if err := m.Lists[len(m.Lists)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWebinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InfoDetail) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoDetail: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoDetail: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueVal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniqueVal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebVal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebVal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			m.DeletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ord", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ord = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWebinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SaveInfoReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SaveInfoReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SaveInfoReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sn = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniqueVal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniqueVal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebVal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WebVal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			m.DeletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ord", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ord = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWebinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SaveResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SaveResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SaveResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWebinfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWebinfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWebinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelInfoReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWebinfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelInfoReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelInfoReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Physical", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Physical = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipWebinfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthWebinfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWebinfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWebinfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWebinfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWebinfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWebinfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWebinfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWebinfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWebinfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWebinfo = fmt.Errorf("proto: unexpected end of group")
)
